backend = "fastresize"
color_space = "lch"
palette = "light16"

check_contrast = true

[templates]
hyprland = { template = 'hyprland.conf', target = '~/.cache/wallust/colors/hyprland.conf' }
kitty = { template = 'kitty.conf', target = '~/.cache/wallust/colors/kitty.conf' }
qt = { template = 'qt.conf', target = '~/.cache/wallust/colors/qt.conf' }
rofi = { template = 'rofi.rasi', target = '~/.cache/wallust/colors/rofi.rasi' }
